# Generated by Django 3.2.6 on 2022-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=255)),
                ('Mobile', models.CharField(error_messages={'unique': 'A account already exists with this mobile number'}, max_length=255, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'A account already exists with this mobile number'}, max_length=254, unique=True)),
                ('id', models.CharField(error_messages={'primary_key': 'This user id is already taken'}, max_length=255, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=255)),
                ('ques', models.IntegerField()),
                ('ans', models.TextField()),
                ('balence', models.CharField(max_length=50)),
                ('leaf', models.CharField(max_length=50)),
                ('premium', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
