# Generated by Django 3.2.6 on 2022-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('code', models.CharField(error_messages={'unique': 'Service code already exists'}, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='balence',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='leaf',
            field=models.CharField(max_length=25),
        ),
    ]
