# Generated by Django 3.2.6 on 2022-11-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_auto_20221105_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.CharField(error_messages={'unique': 'Service code already exists'}, max_length=20, primary_key=True, serialize=False),
        ),
    ]
