# Generated by Django 3.2.6 on 2022-11-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20221105_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('query', models.TextField()),
                ('status', models.CharField(choices=[('Unanswered', 'unanswered'), ('Answered', 'answered')], default='unanswered', max_length=15)),
                ('token', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'HelpDesk',
                'verbose_name_plural': 'HelpDesk',
            },
        ),
    ]
