# Generated by Django 3.2.6 on 2022-11-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_helpdesk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpdesk',
            old_name='user_id',
            new_name='UserId',
        ),
        migrations.AddField(
            model_name='user',
            name='JobTitle',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='A Rapyd Green user'),
        ),
    ]
