# Generated by Django 3.2.6 on 2022-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20221105_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('qty', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'CartItems',
                'verbose_name_plural': 'CartItems',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=15)),
                ('stock', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Items',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AlterField(
            model_name='helpdesk',
            name='UserId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
