# Generated by Django 3.2.6 on 2022-12-04 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend', '0006_auto_20221105_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='no name', max_length=255)),
                ('Mobile', models.CharField(error_messages={'unique': 'A account already exists with this mobile number'}, max_length=255, unique=True)),
                ('JobTitle', models.CharField(default='', max_length=40)),
                ('bio', models.TextField(default='A Rapyd Green user')),
                ('balence', models.CharField(default='0', max_length=20)),
                ('leaf', models.CharField(default='0', max_length=25)),
                ('account_type', models.CharField(default='Basic', max_length=255)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Details',
                'verbose_name_plural': 'User_Details',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
