# Generated by Django 3.2.6 on 2022-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_user_details_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_details',
            options={},
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='account_type',
            new_name='AccountType',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='JobTitle',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='balence',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='leaf',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='username',
        ),
        migrations.AddField(
            model_name='user_details',
            name='Bio',
            field=models.TextField(default='A Rapyd green user'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Leaf',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='user_details',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default='Abcd', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
